[package]
name = "rpipe"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.78"
axum = { version = "0.7.2", features = ["multipart"] }
futures = "0.3"
log = "0.4.20"
tokio = { version = "1.35", features = ["full"] }
tokio-util = { version = "0.7", features = ["io"] }
uuid = { version = "1.6.1", features = ["v4"] }
clap = { version = "4.4.12", features = ["derive"] }
simple_logger = "4.3.3"
reqwest = { version = "0.11.23", features = ["json"] }
openssl = { version = "0.10", features = ["vendored"] }
serde_json = "1.0.109"
