[package]
name = "rpipe"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.72"
axum = { version = "0.6.18", features = ["multipart"] }
futures = "0.3"
log = "0.4.19"
tokio = { version = "1.29", features = ["full"] }
tokio-util = { version = "0.7", features = ["io"] }
uuid = { version = "1.4.0", features = ["v4"] }
clap = { version = "4.3.12", features = ["derive"] }
simple_logger = "4.2.0"
reqwest = "0.11.18"
openssl = { version = "0.10", features = ["vendored"] }