name: docker

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Repo metadata
        id: repo
        uses: actions/github-script@v6
        with:
          script: |
            return context.repo.repo
      - uses: actions/setup-go@v4
        with:
          go-version: "1.20.2"
      - name: Build Go binaries
        run: ./build.sh
      - name: Test
        run: ./test.sh
